### ISSUE TITLE
Errors: unimplemented OBJ format statement 's' on line 's 1' AND convert failed: 6 columns passed, passed data had 3 columns

### ISSUE THREAD

**Issue by jkerman2000** [takecx/obj2schematic#9]
I've exported the OBJ file from Blender, it uses vertex colors and has no MTL file. 
[wtest2.txt](https://github.com/takecx/obj2schematic/files/6737073/wtest2.txt) <---change the extension on this file to obj.

**Comment by takecx** [comment]
@jkerman2000 
Hi 👋 
According to [blender manual](https://docs.blender.org/manual/en/latest/addons/io_scene_obj.html), colored `.obj` file which exported from blender must includes `.mtl` file.
Please check your blender setting!🥺

**Comment by jajaradebela** [comment]
what do you mean im getting the same error and i have a mtl file in the same directory as the obj

**Comment by jajaradebela** [comment]
[untitled.zip](https://github.com/takecx/obj2schematic/files/6824245/untitled.zip)

heres my obj and my mtl

**Comment by jajaradebela** [comment]
okay so i fixed the problem with unimplemented OBJ format statement 's' on line 's 1', but now i am getting this

convert failed:  mapping file does not exists
Traceback (most recent call last):
  File "Obj2SchemticConverter.py", line 241, in <module>
    args.obj_file, args.output_dir, args.h_max, args.w_max)
  File "Obj2SchemticConverter.py", line 38, in __init__
    self.df = self._create_obj_df(obj_path)
  File "Obj2SchemticConverter.py", line 46, in _create_obj_df
    vertices = self._analyze_mtl(obj_path, scene)
  File "Obj2SchemticConverter.py", line 62, in _analyze_mtl
    raise Exception('mapping file does not exists')
Exception: mapping file does not exists_

Edit: this error is now gone and now i am getting:

convert failed:  'NoneType' object has no attribute 'file_name'
Traceback (most recent call last):
  File "Obj2SchemticConverter.py", line 241, in <module>
    args.obj_file, args.output_dir, args.h_max, args.w_max)
  File "Obj2SchemticConverter.py", line 38, in __init__
    self.df = self._create_obj_df(obj_path)
  File "Obj2SchemticConverter.py", line 46, in _create_obj_df
    vertices = self._analyze_mtl(obj_path, scene)
  File "Obj2SchemticConverter.py", line 59, in _analyze_mtl
    img_name = material.texture.file_name
AttributeError: 'NoneType' object has no attribute 'file_name'

this is my mtl file:

#Blender MTL File: 'None'
#Material Count: 1

newmtl Default_OBJ
Ns 323.999994
Ka 1.000000 1.000000 1.000000
Kd 0.800000 0.800000 0.800000
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.000000
d 1.000000
map_Kd
illum 2

i saw the closed issue and i am using an image texture for the obj file, i tried adding just map_Kd to the mtl file but this is probably not how you add it im not very good with obj/mtl

**Comment by takecx** [comment]
@jajaradebela 
You should add texture image path to your `map_Kd` line.

(.mtl)
```mtl
# Blender MTL File: 'None'
# Material Count: 1

newmtl Default_OBJ
Ns 323.999994
Ka 1.000000 1.000000 1.000000
Kd 0.800000 0.800000 0.800000
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.000000
d 1.000000
map_Kd ./your_texture_image.png
illum 2
```
